#!/usr/bin/env python



from nagioscheck import NagiosCheck, UsageError
from nagioscheck import PerformanceMetric, Status
import redis

STATE = ['critical', 'warning', 'ok']
redis_host = 'localhost'
redis_port = 6379

class RateCheck(NagiosCheck):
    version = '0.1.0'
    def __init__(self):
        NagiosCheck.__init__(self)
        self.state = STATE[2]
        self.redis = redis.redis.Redis(host=redis_host, port=redis_port)
        self.add_option('r', 'rate', 'rate', 'rate threshold')
        self.add_option('a','average', 'average', 'average threshold')


    def check(self, opts, args):
        msg = "OK Rates"
        data = self.redis.keys('*.*.*.*')
        
        rate = int (opts.rate or 600)
        average = int (opts.average or 600)
        raise Status(self.state, (msg, None, msg), data)

if __name__ == '__main__':
        RateCheck().run()